---
version: "3.7"

services:

  homeassistant:
    build: .
    volumes:
      - "/data/dockers/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8123:8123"
    restart: unless-stopped
